name: buskoguard_mobile
description: Application mobile BuskoGuard pour la gestion des pointages et profils.

publish_to: 'none' # Ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.14
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true